name: List services in GCP
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: 'write'
  contents: 'read'

jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v1'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/378977059876/locations/global/workloadIdentityPools/github-connect'
          service_account: 'starting-account-wq9tqvj8u074@gareport-1669882853272.iam.gserviceaccount.com'
    - id: 'gcloud'
      name: 'gcloud'
      run: |-
        gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
        gcloud services list
