name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      ## Authenticate to Google Cloud from GitHub Actions via Workload Identity Federation or service account keys
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.1.1